export const HANDLE_REPO_NAME_CHANGE = 'HANDLE_REPO_NAME_CHANGE';
export const HANDLE_USER_NAME_CHANGE = 'HANDLE_USER_NAME_CHANGE';
export const CLEAN_INPUTS = 'CLEAN_INPUTS';
export const HANDLE_SEARCH_BUTTON_CLICK = 'HANDLE_SEARCH_BUTTON_CLICK';
export const UPDATE_ISSUES = 'UPDATE_ISSUES';
export const HANDLE_PAGESIZE_CHANGE = 'HANDLE_PAGESIZE_CHANGE';
export const HANDLE_NEXT_PAGE_CLICK = 'HANDLE_NEXT_PAGE_CLICK';
export const HANDLE_PREV_PAGE_CLICK = 'HANDLE_PREV_PAGE_CLICK';
